ridiculousfish/libdivide

libdivide.h

As discussed in https://github.com/ridiculousfish/libdivide/issues/12 I have made a modification to ```libdivide_u*_branchfree_do()``` so that it uses 1 instruction less.
There are 2 possible ways to implement this:
* Make minor modifications in ```libdivide_u*_branchfree_gen()```, ```libdivide_u*_branchfree_recover()``` and ```libdivide_u*_branchfree_do()```.
* Implement a separate ```libdivide_internal_u*_branchfree_gen``` (probably some other functions need to be duplicated as well).
I chose the first solution because it requires less code and is much easier to implement. Though I have to agree that the second solution would be cleaner at the expense of duplicating some code.
Please let me know what you think about these code changes.

Save 1 instruction in libdivide_u*_branchfree_do()

---

libdivide.h

This pull request implements the enhancement suggested in https://github.com/ridiculousfish/libdivide/issues/19. As you can see below I measured a small speed up using your test program:
```bash
kim@kim-PC /cygdrive/C/Users/kim/Desktop/libdivide-MSVC-intrinsics
$ time ./libdivide_test.exe
Starting int32_t
Starting uint32_t
Starting sint64_t
Starting uint64_t
real    1m44.433s
user    0m0.000s
sys     0m0.030s
kim@kim-PC /cygdrive/C/Users/kim/Desktop/libdivide-master
$ time ./libdivide_test.exe
Starting int32_t
Starting sint64_t
Starting uint32_t
Starting uint64_t
real    1m51.549s
user    0m0.000s
sys     0m0.000s
```

Use __umulh(), __mulh() MSVC intrinsics on WIN64

---

Makefile

`CPP` in makefiles normally stands for "C preprocessor", not "C++".

Makefile: rename CPP as CXX

---

libdivide_test.cpp

Make sure all code using SSE2 is guarded with `LIBDIVIDE_USE_SSE2` define.
As mentioned in #34, but this commit is independent from the build system.

Hide SSE2 code behind #ifdefs

---

libdivide.h

This pull request improves the error handling in libdivide.
Up until now we used **assertions** for error handling but this requires ```LIBDIVIDE_ASSERTIONS_ON``` to be defined by the user and most users don't do it. See e.g. https://github.com/ridiculousfish/libdivide/issues/23
Also, the new branchfree dividers have some tricky restrictions e.g. signed branchfree divider cannot be -1, 0, 1 and unsigned branchfree divider cannot be 0, 1.
For these reasons we need more serious error handling. I have implemented run-time checks for the dividers:
* all dividers !=0
* branchfree dividers != 1
* signed branchfree dividers != -1
The run-time checks are not in the performance critical path i.e. they have been implemented in the divider generation functions. There shouldn't be any measurable …

Improved error handling

---

libdivide.h

```
libdivide/libdivide.h: In function 'libdivide_s32_do':
libdivide/libdivide.h:1275:21: warning: declaration of 'sign' shadows a previous local [-Wshadow]
int32_t sign = (int8_t)more >> 7;
^~~~
libdivide/libdivide.h:1263:14: note: shadowed declaration is here
uint32_t sign = (int8_t)more >> 7;
^~~~
```

Correct -Wshadow warning

---

CMakeLists.txt
libdivide.h
test/multi_file/lib.cpp
test/multi_file/lib.h
test/multi_file/main.cpp

Hi, I've noticed that in the C++ version we place everything inside anonymous namespace. While this theoretically makes it easy to maintain header-only design, I believe this actually makes any use of libdivide::divider in a multi-file project potentially ill-defined.
The problem is that, as each translation unit has its own anonymous namespace, in each translation unit we declare a unique class template libdivide::<anonymous>::divide, so we cannot really pass an instance of divider between translation unit.
`g++` agrees that something is wrong with this approach by issuing a warning similar to
```
warning: ‘IntWithDivider’ has a field ‘IntWithDivider::divider’ whose type uses the anonymous namespace [-Wsubobject-linkage]
struct IntWithDivider {
^~~~~~~~~~~~~~
```
In this pull request I …

Replace anonymous namespace with inline specifiers

---

libdivide.h

Replace the algorithm for counting leading zeros (in the case of no builtin function)
by one that searches the number in larger chunks first.
This can speed up the counting by up to 10x in the case of small numbers (lots of zeros).
Both tester as well as benchmark_branchfree complete successfully with the new approach. It has also been confirmed explicitly that the results of the old and the new approach agree for all numbers less than 10,000,000.
The process of searching larger chunks first before going bitwise can probably be extended even more to speed it up even further, but this way appears to be a good compromise between legibility and speed.

Accelerate counting of leading zeros

---

libdivide.h

https://github.com/ridiculousfish/libdivide/issues/64
\+ remove one trailing space (this is non-significant).

Change exit to abort

---

libdivide.h

AVR int is only 16 bits - force constants to 32-bits where necessary

AVR bug fix

---

test/avr_type_helpers.h

@adbancroft 
The `make_unsigned` trait used by the AVR tests doesn't appear to do the right thing. I think there are some typos. As implemented, it seems to behave as you'd expect from a `make_signed` trait.  Specifically, signed integral types are left unchanged by the trait, and for the unsigned types where there are specialisations, the trait actually *adds* signedness.
This PR ought to fix the issue, I think.

Fix make_unsigned trait in avr_type_helpers.h

---

README.md
constant_fast_div.hpp
test/avr/platformio.ini
test/avr/src/invariant_div_test/constant_macros.h
test/avr/src/invariant_div_test/gen_constant_tests.py
test/fast_div_generator.cpp

A set of predefined templates to speed up division by 16-bit constants.
Template equivalent of #76.

Constant division templates

---

test/DivideTest.h

The `tester` executable wasn't running vector tests: logic error in defining `VECTOR_TESTS` preprocessor symbol in `DivideTest.h`

Tester program: enable vector tests

---

libdivide.h
test/DivideTest.h

Fix #90 
Only occurs under -O3 on GCC x86_64 (v9.3 tested). GCC has built in SSE & AVX2 vector types as well as built in [vector extensions](https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html#Vector-Extensions), including subscription operator. I *think* the original code was clashing with this.

Fix GCC vector alignment and aliasing issues

---

libdivide.h

The current implementation is a workaround: this PR uses the appropriate vector operations to implement 16-bit division for __m256i & __m128i

Implement 16-bit SSE2 & AVX2 vector division

---

libdivide.h
test/DivideTest.h
test/benchmark.cpp
test/benchmark.h
test/benchmark_branchfree.cpp
test/tester.cpp

To restate #96: currently libdivide "dispatches" based on whether its type is `uint32_t`, `uint64_t`, etc. However these types are mapped to a primitive type like `unsigned int`; if say `unsigned long` has the same width then `divider<unsigned long>` will fail to compile since there is no specialization for it.
The idea here is to go back to a dispatch based on the size and signedness of the type, so that `unsigned long` and `unsigned int` will be handled the same. To detect the signedness we avoid `type_traits` which is apparently unavailable in AVR; instead we use the following trick:
T(0) > T(-1)
which will be true only for signed types. We can prevent floating point by throwing in a shift:
(T(0) >> 0) > T(-1)
An inelegant hack for an uncivilized language but it does the job. Fixes …

Fix compilation of primitive types

---

test/benchmark_branchfree.cpp

to avoid the dependence on rtti

Replace typeid(T).name() with type_tag<T>::get_tag()

---

libdivide.h

MSVC does not like T(0) in template arguments. Try (T)0 instead.

Try to fix the MSVC build

---

CMakeLists.txt

Currently the `CMakeLists.txt` file specifies options `BUILD_TESTS` and `BUILD_FUZZERS`. This pull request adds the prefix `LIBDIVIDE_` to the names of both options to help avoid name collisions when using libdivide together with other CMake projects. I've searched libdivide using `git grep`, and the options don't seem to be used in any other file.

Add prefixes to CMake option names

---

CMakeLists.txt

This PR updates the `LIBDIVIDE_VERSION` CMake variable to the same value as contained in `libdivide.h`.

Fix `LIBDIVIDE_VERSION` CMake variable

---

CMakeLists.txt

Currently the libdivide project's `CMakeLists.txt` file sets up tests in a way that makes it possible to run the tests from the build directory by executing the `ctest` command. Yet the `CMakeLists.txt` file does not include the [CTest](https://cmake.org/cmake/help/latest/module/CTest.html) CMake module anywhere. This pull request includes the CTest module in the appropriate location.
I'm actually surprised executing the `ctest` command to run libdivide's tests even worked without including the CTest module in the first place. Maybe one of the other included CMake modules ended up transitively loading the CTest module. This, however, would be undocumented behaviour (AFAIK) that should not be relied on.

Include missing CTest module

---

CMakeLists.txt

This pull request configures the `LIBDIVIDE_BUILD_TESTS` CMake option to be `ON` only when libdivide is being configured as the main project. This is because building tests by default when libdivide is _not_ the main project can unexpectedly include libdivide's tests into the main project's tests. The fix in this pull request is inspired by an analogous fix in another C++ library [here](https://github.com/nlohmann/json/pull/2514).
The issue can be explained as follows. When a user includes libdivide into their CMake project using [`FetchContent`](https://cmake.org/cmake/help/latest/module/FetchContent.html), CMake fully configures and builds libdivide during the main project's configuration phase and includes libdivide into the main project using …

Only build tests when libdivide is the main project

---

README.md

Replace typo “divsion” with ”division” in README.md.

Fix a typo (division/divsion) in README.md

---

library.properties

Add library.properties so we can publish libdivide to [Arduino](https://www.arduino.cc/reference/en/libraries/) & [PlatformIO](https://registry.platformio.org/) registries

Publish libdivide to Arduino & PlatformIO library registries

---

libdivide.h

Libdivide already had `libdivide_s16_do_raw` & `libdivide_u16_do_raw`: this PR expands that idiom to 32 & 64 bit types.
This is useful to save a few bytes of memory on embedded Harvard architecture systems: the magic & more values can be pre-computed and then placed directly at the call site. This places the values in the .text section (ends up in flash memory, plentiful) rather than the .bss section (runtime memory, highly constrained).

Add _do_raw functions for 32 & 64 bit types

---

CMakeLists.txt

prevent unintentionally injecting sanitizer flags into cmake release build (help with reproducibility across linux and macos)
relates to https://github.com/Homebrew/homebrew-core/pull/205519

feat: make sanitizer instrumentation optional

---

libdivide.h

+ rename define from LIBDIVIDE_X64_INTRINSICS to LIBDIVIDE_MULH_INTRINSICS
+ __umulh/__mulh available for x64/arm64

Fix check for __umulh/__mulh intrinsics

---

.github/workflows/full_build.yml

CI MSVC sanitize builds got previously broken by this commit: https://github.com/ridiculousfish/libdivide/commit/f026996e305f2c3ba72404e4c5525b4766a6532a

Fix CI MSVC sanitize builds

---

test/DivideTest.h

Due to multiple threads running tests, initial message appears to be mixed up with output from other threads

Fix output from tester

---

CMakeLists.txt

AArch32 also has NEON, but lacks some of the intrinsics needed. Explicitly check for presence of an AArch64-only intrinsic to make the NEON check fail on AArch32.
Fixes		#102

Only enable NEON on AArch64

---

libdivide.h

`__builtin_clz`/`__builtin_clzll` can be used in constexpr function with gcc/clang. This change makes them constexpr for msvc as well.

Make __builtin_clz/__builtin_clzll constexpr to match gcc/clang

---

libdivide.h

This change improves code generation in 32-bit builds (shorter code, uses less stack).

Preserve order of params when calling libdivide_mullhi

---

libdivide.h

Simply check for the value of the `__STDC_HOSTED__` macro before including `<stdlib.h>` or `<stdio.h>` and others.
Moreover, as an idea for future changes, you could also add some checks for user-provided `LIBDIVIDE_{ERROR|ASSERT}`, as printing to the screen and aborting the program is not always a good thing to do anyways (and is sometimes not even possible, in the case of a freestanding environment)

Update libdivide.h to support `-ffreestanding` targets

---

test/benchmark.cpp
test/benchmark_branchfree.cpp
test/fast_div_generator.cpp
test/tester.cpp

`extern "c" int main()` is not allowed in C++, [the standard](https://isocpp.org/files/papers/N4860.pdf) says that:
> The main function shall not be declared with a linkage-specification (9.11). A program that declares a variable main at global scope, or that declares a function main at global scope attached to a named module, or that declares the name main with C language linkage (in any namespace) is ill-formed.
The checking of the C++ language standard has become stricter since GCC 15, so test code will report errors at compile time:
Fix this kind of error by removing illegal `extern "C"` declares.

Fix GCC 15 compiler errors
